clc;
clear all;
close all;
theta = linspace (0,180,361) ;
svv=abs (cosd (theta) ).^2;
shv=abs (sind (theta) ).^2*0.2;
shh=abs (cosd (theta) ) .^2;
svh=abs (sind (theta) ).^2*0.9;
XPD_v=10*log10(svv./shv);
XPD_v=10*log10(shh./svh);
figure;
subplot (2,2,1);
plot (theta, 10*log10(svv), 'b', 'LineWidth', 1.5) ;hold on;
plot (theta, 10*log10(shv),'r -- ','LineWidth',1.5);
xlabel ('Angle(degrees)'); ylabel('power(dB)');
title ('Verticle Transmit:Co-pol vs Cross-pol') ;
legend ('co-pol (svv) ') , 'cross-pol (shv) ';grid on;
subplot (2,2,2);
plot (theta, XPD_v, 'k', 'LineWidth', 1.5) ;hold on;
xlabel ('Angle (degrees)'); ylabel('power(dB)');
title ('Verticle Transmit:Co-pol vs Cross-pol') ;
legend ('co-pol (svv) ') , 'cross-pol (shv) ';grid on;
subplot (2,2,3);
plot (theta, 10*log10(shh), 'b','LineWidth', 1.5) ;hold on;
plot (theta, 10*log10(svh),'r -- ','LineWidth', 1.5);
xlabel ('Angle (degrees)'); ylabel('power(dB)');
title ('Horizontal Transmit:Co-pol vs Cross-pol');
legend ('co-pol (svv) ') , 'cross-pol (shv) ';grid on;
subplot (2,2,4);
plot (theta, XPD_v, 'k' , 'LineWidth' , 1.5) ;hold on;
xlabel ('Angle(degrees)'); ylabel('power(dB)');
title ('Horizontal Transmit:Co-pol vs Cross-pol');
legend ('co-pol (svv) ') , 'cross-pol (shv) ';grid on;