clc;
clear all;
close all;
format short;
beta=linspace(0.1,10,200);
c=3e8;
omega_nd=c*beta;
vp_nd=omega_nd./beta;
vg_nd=gradient(omega_nd,beta(2)-beta(1));
fprintf('Non-Dispersive:vp=%.4f m/s,vg=%.4f m/s \n',vp_nd(50),vg_nd(50));
g=9.81;
omega_d=sqrt(g.*beta);
vp_d=omega_d./beta;
vg_d=gradient(omega_d,beta(2)-beta(1));
fprintf('Dispersive:vp=%.4f m/s,vg=%.4f m/s \n',vp_d(50),vg_d(50));
figure;
subplot(2,1,1);
plot(beta,vp_nd,'b','LineWidth',1.5);hold on;
plot(beta,vg_nd,'r-','LineWidth',1.5);
xlabel('beta(rad/m)');ylabel('Velocity(m/s)');
title('Non-Dispersive Medium(Free space)');
legend('phase velocity v_p','Group velocity v_g');
grid on;
subplot(2,1,2);
plot(beta,vp_d,'b','LineWidth',1.5);hold on;
plot(beta,vg_d,'r-','LineWidth',1.5);
xlabel('beta(rad/m)');ylabel('Velocity(m/s)');
title('Dispersive Medium');
legend('phase velocity v_p','Group velocity v_g');
grid on;